name: Test IPython beamline profiles

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  testing_beamline_profiles:
    name: ${{ matrix.repos.beamline-acronym }}-${{ matrix.repos.repo }}-${{ matrix.repos.branch }}-py311
    strategy:
      fail-fast: false
      matrix:
        repos:
          # - org: "NSLS-II-AMX"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "amx"
          # - org: "NSLS-II-BMM"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "bmm"
          # - org: "NSLS-II-CHX"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "chx"
          # # TODO: revert the CMS config once the PR is merged:
          # - org: "thomashopkins32"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "cms"
          # # - org: "NSLS-II-CMS"
          # #   repo: "profile_collection"
          # #   branch: "master"
          # #   beamline-acronym: "cms"
          # - org: "NSLS-II-CSX"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "csx"
          - org: "NSLS-II-ESM-1"
            repo: "profile_collection"
            branch: "2022-lustre-migration"
            beamline-acronym: "arpes"
          # - org: "NSLS-II-ESM-2"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "xpeem"
          # - org: "NSLS-II-FMX"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "fmx"
          # - org: "NSLS-II-FXI"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "fxi"
          # - org: "NSLS-II-HEX"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "hex"
          # - org: "NSLS-II-HXN"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "hxn"
          # - org: "NSLS-II-IOS"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "ios"
          # - org: "NSLS-II-ISR"
          #   repo: "profile_D-hutch"
          #   branch: "2025-2.0"
          #   beamline-acronym: "isr"
          # - org: "NSLS-II-IXS"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "ixs"
          # - org: "NSLS-II-LIX"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "lix"
          # - org: "NSLS-II-NYX"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "nyx"
          # - org: "NSLS-II-PDF"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "pdf"
          # - org: "NSLS-II-QAS"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "qas"
          # - org: "NSLS-II-SIX"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "six"
          # - org: "NSLS-II-SMI"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"  # the branch is created off of the 'data-security' branch
          #   beamline-acronym: "smi"
          #   beamline-redis-prefix: "swaxs-"
          # - org: "NSLS-II-SRX"
          #   repo: "profile_collection"
          #   branch: "master"
          #   beamline-acronym: "srx"
          # - org: "NSLS-II-SST"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "sst"
          # - org: "NSLS-II-SST"
          #   repo: "profile_collection_ucal"
          #   branch: "2025-2.0"
          #   beamline-acronym: "sst"
          # - org: "NSLS-II-SST"
          #   repo: "profile_collection_haxpes"
          #   branch: "2025-2.0"
          #   beamline-acronym: "sst"
          # - org: "NSLS-II-TES"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "tes"
          # - org: "NSLS-II-TST"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "tst"
          # - org: "NSLS-II-XFM"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "xfm"
          # - org: "NSLS-II-XFM"
          #   repo: "profile-collection-maia"
          #   branch: "2025-2.0"
          #   beamline-acronym: "xfm"
          # - org: "NSLS-II-XFP"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "xfp"
          # - org: "NSLS-II-XPD"
          #   repo: "profile_collection"
          #   branch: "2025-2.0"
          #   beamline-acronym: "xpd"
          # - org: "NSLS-II-XPD-tomo"
          #   repo: "profile_collection"
          #   branch: "main"
          #   beamline-acronym: "xpdd"

    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests Against Beamline Profiles
        uses: NSLS2/gha-beamline-integration-test@2025-1.0-test
        with:
          conda_env_url: "https://zenodo.org/records/14862443/files/2025-1.0-py311-tiled.tar.gz"
          conda_env_md5: "3b1074c0827ee3baf0cdcd64917b9afa"
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline-acronym }}"
          beamline-redis-prefix: "${{ matrix.repos.beamline-redis-prefix }}"
