name: Test IPython beamline profiles

on:
  push:
  pull_request:
  workflow_dispatch:
  workflow_call:
    inputs:
      version: # the variable you can use in place of a matrix
        required: true
        type: string

jobs:
  testing_beamline_profiles:
    name: ${{ matrix.repos.beamline-acronym }}-${{ matrix.repos.repo }}-${{ matrix.repos.branch }}-py311
    strategy:
      fail-fast: false
      matrix:
        repos:
          - org: "NSLS2"
            repo: "amx-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "amx"
          - org: "NSLS2"
            repo: "bmm-profile-collection"
            branch: "main"
            beamline-acronym: "bmm"
          - org: "NSLS2"
            repo: "chx-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "chx"
          - org: "NSLS2"
            repo: "cms-profile-collection"
            branch: "main"
            beamline-acronym: "cms"
          - org: "NSLS2"
            repo: "csx-profile-collection"
            branch: "main"
            beamline-acronym: "csx"
          - org: "NSLS2"
            repo: "esm-arpes-profile-collection"
            branch: "main"
            beamline-acronym: "esm"
            beamline-endstation: "arpes"
            beamline-redis-prefix: "arpes-"
          - org: "NSLS2"
            repo: "esm-xpeem-profile-collection"
            branch: "main"
            beamline-acronym: "esm"
            beamline-endstation: "xpeem"
            beamline-redis-prefix: "xpeem-"
          - org: "NSLS2"
            repo: "fmx-profile-collection"
            branch: "main"
            beamline-acronym: "fmx"
          - org: "NSLS2"
            repo: "fxi-profile-collection"
            branch: "main"
            beamline-acronym: "fxi"
          - org: "NSLS2"
            repo: "hex-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "hex"
          - org: "NSLS2"
            repo: "hxn-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "hxn"
          - org: "NSLS2"
            repo: "ios-profile-collection"
            branch: "main"
            beamline-acronym: "ios"
          - org: "NSLS2"
            repo: "isr-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "isr"
          - org: "NSLS2"
            repo: "ixs-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "ixs"
          - org: "NSLS2"
            repo: "lix-profile-collection"
            branch: "master"
            beamline-acronym: "lix"
          - org: "NSLS2"
            repo: "nyx-profile-collection"
            branch: "main"
            beamline-acronym: "nyx"
          - org: "NSLS2"
            repo: "pdf-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "pdf"
          - org: "NSLS2"
            repo: "qas-profile-collection"
            branch: "main"
            beamline-acronym: "qas"
          - org: "NSLS2"
            repo: "six-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "six"
          - org: "NSLS2"
            repo: "smi-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "smi"
            beamline-redis-prefix: "swaxs-"
          - org: "NSLS2"
            repo: "srx-profile-collection"
            branch: "main"
            beamline-acronym: "srx"
          - org: "NSLS2"
            repo: "sst-rsoxs-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "sst"
          - org: "NSLS2"
            repo: "sst-nexafs-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "sst"
          - org: "NSLS2"
            repo: "sst-haxpes-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "sst"
          - org: "NSLS2"
            repo: "tes-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "tes"
          - org: "NSLS2"
            repo: "tst-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "tst"
          - org: "NSLS2"
            repo: "xfm-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "xfm"
          - org: "NSLS2"
            repo: "xfm-maia-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "xfm"
          - org: "NSLS2"
            repo: "xfp-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "xfp"
          - org: "NSLS2"
            repo: "xpd-profile-collection"
            branch: "2025-2.0"
            beamline-acronym: "xpd"
          - org: "NSLS-II-XPD-tomo"
            repo: "profile_collection"
            branch: "main"
            beamline-acronym: "xpdd"

    runs-on: ubuntu-latest
    steps:
      - name: Run Integration Tests Against Beamline Profiles
        uses: NSLS2/gha-beamline-integration-test@2025-1.0-test
        with:
          conda_env_url: "https://zenodo.org/records/15171538/files/2025-2.0-py311-tiled.tar.gz"
          conda_env_md5: "3d705483eab31648fae7cf0ce9a77e72"
          org: "${{ matrix.repos.org }}"
          repo: "${{ matrix.repos.repo }}"
          branch: "${{ matrix.repos.branch }}"
          beamline-acronym: "${{ matrix.repos.beamline-acronym }}"
          beamline-endstation: "${{ matrix.repos.beamline-endstation }}"
          beamline-redis-prefix: "${{ matrix.repos.beamline-redis-prefix }}"
